
# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Environment variables for build (these should be set in Netlify UI)
# MONGODB_URI = "your-mongodb-connection-string"
# MONGODB_DB = "idealink"